FROM python:3.7-slim

WORKDIR /app

ADD scale_test /app/scale_test

RUN cd scale_test && pip install -r requirements.txt

ENV KEY_FILE_PATH=/data/secrets/key.json
ENV FILE_UPLOAD_URL=http://localhost:8888/v1
ENV TARGET_HOST_URL=http://localhost:8080

ENV NUM_USERS=20
ENV HATCH_RATE=1
ENV TEST_DURATION_MINUTES=10

EXPOSE 8089
CMD locust --host=${TARGET_HOST_URL} -f /app/scale_test/locusts/secondary_analysis.py --csv=results